os: linux
dist: focal
language: java
jdk:
  - oraclejdk15
before_deploy:
  - mvn package
after_deploy:
  - docker build -t ghcr.io/nils-witt/s-plan_dataconnector:"$DOCKER_TAG" .
  - docker tag ghcr.io/nils-witt/s-plan_dataconnector:"$DOCKER_TAG" ghcr.io/nils-witt/s-plan_dataconnector:"$TRAVIS_COMMIT"
  - echo "$GITHUB_KEY" | docker login ghcr.io -u "$GITHUB_USER" --password-stdin
  - docker push ghcr.io/nils-witt/s-plan_dataconnector
after_success:
  - zip -r "$TRAVIS_BRANCH".zip artifacts
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
    -T "$TRAVIS_BRANCH".zip
    --key /tmp/sftp_rsa
    sftp://${SFTP_USER}:nopass@annika.cloud.nils-witt.de/dataRoot/files-webserver/releases/S-Plan_DataConnector/